input.onButtonPressed(Button.A, function () {
    basic.clearScreen()
    for (let index = 0; index < 1; index++) {
        basic.pause(500)
        sprite.set(LedSpriteProperty.Y, 2)
        basic.pause(500)
        sprite.set(LedSpriteProperty.Y, 1)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 2)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 1)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 1)
        sprite.set(LedSpriteProperty.Y, 2)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 1)
        sprite.set(LedSpriteProperty.Y, 3)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 2)
        sprite.set(LedSpriteProperty.Y, 3)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 3)
        sprite.set(LedSpriteProperty.Y, 3)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 3)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 2)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 1)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 0)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 3)
        sprite.set(LedSpriteProperty.Y, 0)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 2)
        sprite.set(LedSpriteProperty.Y, 0)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 1)
        sprite.set(LedSpriteProperty.Y, 0)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 0)
        sprite.set(LedSpriteProperty.Y, 0)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 0)
        sprite.set(LedSpriteProperty.Y, 1)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 0)
        sprite.set(LedSpriteProperty.Y, 2)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 0)
        sprite.set(LedSpriteProperty.Y, 3)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 0)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 1)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 2)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 3)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 3)
        sprite.set(LedSpriteProperty.Y, 4)
        basic.pause(500)
        sprite.set(LedSpriteProperty.X, 4)
        sprite.set(LedSpriteProperty.Y, 4)
    }
})
let sprite: game.LedSprite = null
sprite = game.createSprite(3, 3)
